name: Hola Mundo

on: [push]

jobs: 
  hola:
    runs-on: ubuntu-latest

    steps:
    - name: hola mundo
      run: echo "Hola Mundo"

    - name: touch file
      run: touch hola.txt

    - name: Set text
      run: echo "Hola Mundo" >> hola.txt

    - name: Read file
      run: cat hola.txt
  
  other:
    runs-on: ubuntu-latest

    needs: [hola]
    
    steps:
    - name: LS
      run: ls -al

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
      with:
        node-version: latest

    - name: node version
      run: node --version

    - name: PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3' 

    - name: php version
      run: php --version

  say-hello:
    runs-on: ubuntu-latest

    env:
      MY_VAR: Mi variable de entorno
    
    steps: 
      - name: Test
        run: echo "Valor ${{ vars.MY_VARIABLE_2 }}"

      - name: Secret
        run: echo "Secret ${{ secrets.MY_SECRET}}"

  local-action:
    runs-on: ubuntu latest

    steps:
      - name: Ls
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY}}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 127.0.1.1 >> ~/.ssh/known_hosts

          cat ~/.ssh/known_hosts

  
